name: Monorepo Release
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get matrix
        id: get-matrix
        uses: tj-actions/changed-files@v46
        with:
          path: ''
          dir_names: true
          json: true
          escape_json: false
          dir_names_exclude_current_dir: false
          dir_names_max_depth: 1
          files: ''
          files_ignore: |
            .github/**

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix).include[0] }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.appId }}
          private-key: ${{ secrets.appPrivateKey }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies
        run: |
          cd "${{ matrix.module }}"
          npm install
      - name: Get GitHub App User ID
        id: get-user-id
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      - name: Release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          cd "${{ matrix.module }}"
          npx semantic-release -t "${{ matrix.module }}"/'v${version}'
