name: Monorepo Release
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get matrix
        id: get-matrix
        uses: tj-actions/changed-files@v46
        with:
          path: ''
          dir_names: true
          json: true
          escape_json: false
          dir_names_exclude_current_dir: false
          dir_names_max_depth: 1
          files: ''
          files_ignore: |
            .github/**
            scripts/**

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies
        run: |
          cd "${{ matrix.module }}"
          npm install
      - name: Generate token
        env:
          APP_ID: ${{ secrets.appId }}
          PRIVATE_KEY: ${{ secrets.appPrivateKey }}
        if: ${{ env.APP_ID != null && env.PRIVATE_KEY != null }}
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.appId }}
          private_key: ${{ secrets.appPrivateKey }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          cd "${{ matrix.module }}"
          npx semantic-release -t "${{ matrix.module }}"/'${version}'
